#!/usr/bin/env python
"""List Packages"""

import argparse
import configparser

from Packagecloud import get_all_packages
from Packagecloud import show_packagelist


def configure():
    """Configure"""
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', required=True,
                        help='Config file')
    parser.add_argument('--srcrepo', required=True,
                        help='Source Repository')
    parser.add_argument('--distro', required=False,
                        help='Filter selection by distro')
    parser.add_argument('--version', required=False,
                        help='Filter selection by package version')
    parser.add_argument('--name', required=False,
                        help='Filter selection by package name')
    parser.add_argument('--type', required=False,
                        help='Filter selection by package type')
    parser.add_argument('--match', required=False,
                        help='Filter selection by filename substring match')
    parser.add_argument('--dlurl', required=False,
                        help='Display download URLs')
    parser.add_argument('--wget', required=False,
                        help='Display wget commands')
    parser.add_argument('--debug', action='store_true',
                        help='Print debug output')
    args = parser.parse_args()

    config = configparser.SafeConfigParser()
    config.read(args.config)

    token = config.get('packagecloud', 'token')
    http_scheme = config.get('packagecloud', 'http_scheme')
    api_domain = config.get('packagecloud', 'api_domain')
    api_version = config.get('packagecloud', 'api_version')

    conf = {
        'domain_base': '{}://{}:@{}'.format(
            http_scheme, token, api_domain),
        'url_base': '{}://{}:@{}/api/{}'.format(
            http_scheme, token, api_domain, api_version),
        'repouser': config.get('packagecloud', 'repo_user'),
        'srcrepo': args.srcrepo,
        'debug': args.debug,
        'distro': args.distro,
        'version': args.version,
        'name': args.name,
        'type': args.type,
        'match': args.match,
        'args': args
    }

    return conf


def main():
    """Main"""
    conf = configure()

    packages = get_all_packages(conf['repouser'],
                                conf['srcrepo'], conf)

    show_packagelist(conf['repouser'], conf['srcrepo'], packages,
                     conf['distro'], conf['version'], conf['name'],
                     conf['match'], conf['type'])

main()
