#!/usr/bin/env python -u
"""Destroy Packages"""
from __future__ import print_function
import argparse
import ConfigParser

from Packagecloud import abort
from Packagecloud import destroy_package
from Packagecloud import get_all_packages
from Packagecloud import show_packagelist


def configure():
    """Configure"""
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', required=True,
                        help='Config file')
    parser.add_argument('--srcrepo', required=True,
                        help='Source Repository')
    parser.add_argument('--interactive', action='store_true',
                        help='Interactive Mode')
    parser.add_argument('--force', action='store_true',
                        help='Skip confirmation prompt')
    parser.add_argument('--distro', required=False,
                        help='Filter selection by distro')
    parser.add_argument('--version', required=False,
                        help='Filter selection by package version')
    parser.add_argument('--name', required=False,
                        help='Filter selection by package name')
    parser.add_argument('--match', required=False,
                        help='Filter selection by filename substring match')
    parser.add_argument('--type', required=False,
                        help='Filter selection by package type')
    parser.add_argument('--debug', action='store_true',
                        help='Print debug output')
    args = parser.parse_args()

    config = ConfigParser.SafeConfigParser()
    config.read(args.config)

    token = config.get('packagecloud', 'token')
    http_scheme = config.get('packagecloud', 'http_scheme')
    api_domain = config.get('packagecloud', 'api_domain')
    api_version = config.get('packagecloud', 'api_version')

    conf = {
        'domain_base': '{}://{}:@{}'.format(
            http_scheme, token, api_domain),
        'url_base': '{}://{}:@{}/api/{}'.format(
            http_scheme, token, api_domain, api_version),
        'repouser': config.get('packagecloud', 'repo_user'),
        'srcrepo': args.srcrepo,
        'debug': args.debug,
        'interactive': args.interactive,
        'force': args.force,
        'distro': args.distro,
        'version': args.version,
        'name': args.name,
        'type': args.type,
        'match': args.match,
        'args': args
    }

    return conf


def main():
    """Main"""
    conf = configure()

    packages = get_all_packages(conf['repouser'], conf['srcrepo'], conf)

    if not conf['force']:
        show_packagelist(conf['repouser'], conf['srcrepo'], packages,
                         conf['distro'], conf['version'], conf['name'],
                         conf['match'], conf['type'])

    if not conf['interactive'] and not conf['force']:
        yankall = raw_input("Are you sure you want to yank all (y/N)? "). \
            lower() == 'y'
        if not yankall:
            abort('Aborted', 1)

    yancount = 0
    skpcount = 0
    errcount = 0
    yank = True
    for package in packages:
        if conf['distro'] and not package['distro_version'] == conf['distro']:
            continue
        elif conf['version'] and not package['version'] == conf['version']:
            continue
        elif conf['name'] and not package['name'] == conf['name']:
            continue
        elif conf['type'] and not conf['type'] == package['type']:
            continue
        elif conf['match'] and not conf['match'] in package['filename']:
            continue

        print('Going to yank {:<45} from {:>15}/{:<15}  '.format(
            package['filename'], conf['repouser'], conf['srcrepo']), end='')

        if conf['interactive']:
            yank = raw_input("Yank this package (y/N)? ").lower() == 'y'

        if yank:
            yankresult = destroy_package(package, conf)
            if yankresult:
                print('[OK]')
                yancount += 1
            else:
                print('[ERROR]')
                errcount += 1
        else:
            print('Skipped {}'.format(package['filename']))
            skpcount += 1

    print('-----------------------------------------')
    print('Total packages processed: ', (yancount + skpcount + errcount))
    print('Yanked:  ', yancount)
    print('Skipped: ', skpcount)
    print('Errors:  ', errcount)

main()
